### ISSUE TITLE
otbr-agent.service does not start upon reboot sometimes

### ISSUE THREAD

**Issue by purvisb** [openthread/ot-br-posix#741] opened 2021-03-18 00:42 UTC
**Describe the bug** 
otbr-agent.service does not start upon reboot sometimes. I believe as a result of this - ot-ctl is not able to run commands.

Sometimes it does work. I can't identify the pattern.

**To Reproduce** 

Git commit id: 2e347449994a90e9082dc3c56f0a0d9004922201

hardware platform: nRF 52840-mdk from maker diary (not a dongle). Border router is running on raspberry pi.

[I followed this doc](https://openthread.io/guides/border-router/build#build-and-flash-rcp)

**Expected behavior** 
otbr-agent.service starts and i can run commands with ot-ctl

**Console/log output** 
```
pi@raspberrypi:~ $ sudo /etc/init.d/otbr-agent status
● otbr-agent.service - Border Router Agent
   Loaded: loaded (/lib/systemd/system/otbr-agent.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-03-18 00:41:00 UTC; 4s ago
  Process: 1776 ExecStart=/usr/sbin/otbr-agent $OTBR_AGENT_OPTS (code=exited, status=5)
 Main PID: 1776 (code=exited, status=5)

Mar 18 00:41:00 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
```

```
pi@raspberrypi:~ $ journalctl -u otbr-agent.service
-- Logs begin at Thu 2021-03-18 00:40:26 UTC, end at Thu 2021-03-18 00:41:15 UTC. --
Mar 18 00:40:29 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:40:29 raspberrypi otbr-agent[417]: Running 0.2.0-2e347449
Mar 18 00:40:29 raspberrypi otbr-agent[417]: Thread interface wpan0
Mar 18 00:40:29 raspberrypi otbr-agent[417]: Backbone interface
Mar 18 00:40:29 raspberrypi otbr-agent[417]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:40:29 raspberrypi otbr-agent[417]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:40:30 raspberrypi otbr-agent[417]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:40:30 raspberrypi otbr-agent[417]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:40:30 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:40:30 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:40:30 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:40:35 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:40:35 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:40:35 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:40:35 raspberrypi otbr-agent[702]: Running 0.2.0-2e347449
Mar 18 00:40:35 raspberrypi otbr-agent[702]: Thread interface wpan0
Mar 18 00:40:35 raspberrypi otbr-agent[702]: Backbone interface
Mar 18 00:40:35 raspberrypi otbr-agent[702]: [WARN]-PLAT----: Unexpected Spinel transaction message: 6
Mar 18 00:40:35 raspberrypi otbr-agent[702]: [WARN]-PLAT----: Error processing response: Drop
Mar 18 00:40:37 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
Mar 18 00:40:37 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:40:37 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:40:42 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:40:42 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:40:42 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:40:42 raspberrypi otbr-agent[1411]: Running 0.2.0-2e347449
Mar 18 00:40:42 raspberrypi otbr-agent[1411]: Thread interface wpan0
Mar 18 00:40:42 raspberrypi otbr-agent[1411]: Backbone interface
Mar 18 00:40:43 raspberrypi otbr-agent[1411]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:40:43 raspberrypi otbr-agent[1411]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:40:43 raspberrypi otbr-agent[1411]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:40:43 raspberrypi otbr-agent[1411]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:40:43 raspberrypi otbr-agent[1411]: [CRIT]-PLAT----: platformConfigureTunDevice() at ../../third_party/openthread/repo/src/posix/platform/netif.cpp:1299: Device or resource bu
Mar 18 00:40:43 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:40:43 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:40:43 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:40:48 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:40:48 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:40:48 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:40:48 raspberrypi otbr-agent[1631]: Running 0.2.0-2e347449
Mar 18 00:40:48 raspberrypi otbr-agent[1631]: Thread interface wpan0
Mar 18 00:40:48 raspberrypi otbr-agent[1631]: Backbone interface
Mar 18 00:40:49 raspberrypi otbr-agent[1631]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:40:49 raspberrypi otbr-agent[1631]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:40:49 raspberrypi otbr-agent[1631]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:40:49 raspberrypi otbr-agent[1631]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:40:49 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:40:49 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:40:49 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:40:54 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:40:54 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:40:54 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: Running 0.2.0-2e347449
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: Thread interface wpan0
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: Backbone interface
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:40:54 raspberrypi otbr-agent[1705]: [CRIT]-PLAT----: platformConfigureTunDevice() at ../../third_party/openthread/repo/src/posix/platform/netif.cpp:1299: Device or resource bu
Mar 18 00:40:54 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:40:54 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:40:54 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:41:00 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:41:00 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:41:00 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: Running 0.2.0-2e347449
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: Thread interface wpan0
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: Backbone interface
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:41:00 raspberrypi otbr-agent[1776]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:41:00 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:41:00 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:41:00 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:41:05 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:41:05 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:41:05 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:41:05 raspberrypi otbr-agent[1852]: Running 0.2.0-2e347449
Mar 18 00:41:05 raspberrypi otbr-agent[1852]: Thread interface wpan0
Mar 18 00:41:05 raspberrypi otbr-agent[1852]: Backbone interface
Mar 18 00:41:05 raspberrypi otbr-agent[1852]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:41:05 raspberrypi otbr-agent[1852]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:41:06 raspberrypi otbr-agent[1852]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:41:06 raspberrypi otbr-agent[1852]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:41:06 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:41:06 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:41:06 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
Mar 18 00:41:11 raspberrypi systemd[1]: otbr-agent.service: Service hold-off time over, scheduling restart.
Mar 18 00:41:11 raspberrypi systemd[1]: Stopped Border Router Agent.
Mar 18 00:41:11 raspberrypi systemd[1]: Started Border Router Agent.
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: Running 0.2.0-2e347449
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: Thread interface wpan0
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: Backbone interface
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: [NOTE]-PLAT----: RCP API Version: 3
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5400, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
Mar 18 00:41:11 raspberrypi otbr-agent[1917]: [INFO]-CORE----: Non-volatile: ... pid:0x5db3aa72, mlecntr:0x1fd8, maccntr:0x1f4a, mliid:9b203891cbcfffcc}
Mar 18 00:41:11 raspberrypi systemd[1]: otbr-agent.service: Main process exited, code=exited, status=5/NOTINSTALLED
Mar 18 00:41:11 raspberrypi systemd[1]: otbr-agent.service: Unit entered failed state.
Mar 18 00:41:11 raspberrypi systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
```

**Comment by simonlingoogle** [comment] 2021-03-18 02:14
> platformConfigureTunDevice() at ../../third_party/openthread/repo/src/posix/platform/netif.cpp:1299: Device or resource bu

This happens when `otbr-agent` can not create the TUN device `wpan0`. You can try remove the zombie wpan0 device:
```bash
$ sudo ip link del wpan0
```

The `wpan0` device may not be properly removed when otbr-agent crashes. But I am not aware of any other case that it might happen. 

Could you give more information on when this issue can happen? Thanks.

**Comment by purvisb** [comment] 2021-03-20 03:09
This seems to resolve the problem. I'm fine with this being closed

I'm sorry, but I failed to identify a pattern for this issue. It may or may not happen on a reboot. Thats all I can say that seems relevant. let me know if there's some other specific details that are needed.

**Comment by simonlingoogle** [comment] 2021-03-22 01:23
We are considering a fix for otbr-agent to always take over the `wpan0` TUN interface even if the TUN interface already exists.
This should make otbr-agent more robustness, despite the fact that it's unclear why `wpan0` was not removed. 

We can close this issue after the fix is merged.

**Comment by simonlingoogle** [comment] 2021-04-08 02:28
Hi @purvisb ,

We have a draft fix for this issue: https://github.com/openthread/openthread/pull/6406. 
We couldn't verify it because we can't reproduce this exact issue locally. 
Could you help verify if the fix works if you come across the issue again?

Thanks.

**Comment by purvisb** [comment] 2021-04-12 19:37
@simonlingoogle Apologies for the delay. I am aware of this - I'm aiming to get back to you next weekend.

**Comment by purvisb** [comment] 2021-04-19 04:51
I cloned [superwhd/openthread](https://github.com/superwhd/openthread/tree/otbr-takeover-tun) and switched to the otbr-takeover-tun branch. I Built the RCP firmware from that repo and burned it into the chip. 

I commented out the temporary fix from my bootscript: `sudo ip link del wpan0`

After a couple of reboots, the issue came up again. Let me know if I'm implementing the drafted fix correctly.

**Comment by simonlingoogle** [comment] 2021-04-19 06:34
Hi @purvisb 

Thanks for the feedback. 

In the case if the issue, when there is a zombie `wpan0` interface, what is the output of running otbr-agent manually?

e.g. 
```
$ sudo otbr-agent -d 7 -v spinel+hdlc+uart:///dev/ttyUSB0 -I wpan0
```

**Comment by purvisb** [comment] 2021-04-20 16:48
@simonlingoogle 
```
pi@raspberrypi:~ $ sudo otbr-agent -d 7 -v spinel+hdlc+uart:///dev/ttyACM0 -I wpan0
otbr-agent[22754]: Running 0.2.0-2e347449
otbr-agent[22754]: Thread interface wpan0
otbr-agent[22754]: Backbone interface
otbr-agent[22754]: [INFO]-PLAT----: RCP reset: RESET_POWER_ON
otbr-agent[22754]: [NOTE]-PLAT----: RCP API Version: 3
otbr-agent[22754]: [INFO]-CORE----: Non-volatile: Read NetworkInfo {rloc:0x5c00, extaddr:6222f52a5b9581e6, role:Leader, mode:0x0f, version:2, keyseq:0x0, ...
otbr-agent[22754]: [INFO]-CORE----: Non-volatile: ... pid:0xe381c38, mlecntr:0x1b0a8, maccntr:0x23a9c, mliid:9b203891cbcfffcc}
otbr-agent[22754]: [CRIT]-PLAT----: platformConfigureTunDevice() at ../../third_party/openthread/repo/src/posix/platform/netif.cpp:1299: Device or resource busy

```

**Comment by simonlingoogle** [comment] 2021-04-21 02:54
@purvisb 

I noticed that your program still crashed at `src/posix/platform/netif.cpp:1299`, however in @superwhd 's fix branch, there is no longer a `VerifyOrDie` statement at line 1299:
```c++
    if (ioctl(sTunFd, TUNSETIFF, static_cast<void *>(&ifr)) < 0) // line 1299
    {
        ifr.ifr_flags = IFF_TUN | IFF_NO_PI;
        VerifyOrDie(ioctl(sTunFd, TUNSETIFF, static_cast<void *>(&ifr)) == 0, OT_EXIT_ERROR_ERRNO);
        VerifyOrDie(ioctl(sTunFd, TUNSETPERSIST, 0) == 0, OT_EXIT_ERROR_ERRNO);
        close(sTunFd);
        sTunFd = open(OPENTHREAD_POSIX_TUN_DEVICE, O_RDWR | O_CLOEXEC | O_NONBLOCK);
        VerifyOrDie(sTunFd >= 0, OT_EXIT_ERROR_ERRNO);
        ifr.ifr_flags = IFF_TUN | IFF_NO_PI | static_cast<short>(IFF_TUN_EXCL);
        VerifyOrDie(ioctl(sTunFd, TUNSETIFF, static_cast<void *>(&ifr)) == 0, OT_EXIT_ERROR_ERRNO);
    }
    VerifyOrDie(ioctl(sTunFd, TUNSETLINK, ARPHRD_VOID) == 0, OT_EXIT_ERROR_ERRNO);
```

Can you verify if you are using the correct openthread repo?

One thing to note is that `script/bootstrap` will reset the submodules. You change to openthread submodule may be reverted.

**Comment by jwhui** [comment] 2021-07-20 15:14
Closing stale issue.

**Closed by jwhui** 2021-07-20 15:14 UTC
