### ISSUE TITLE
Running RCP Image on Ubuntu System and Unable to establish communication Between RCP and OTBR-AGENT (Openthread communication)

### ISSUE THREAD

**Issue by dipVyas92** [openthread/ot-br-posix#1849] opened 2023-05-02 07:57 UTC
I have purchased new K32W USB dongles. I am trying to run openthread sample example on an Ubuntu machine with a K32W dongle.

I have created RCP image for k32w dongle from openthread github.(https://github.com/openthread/ot-nxp/blob/main/src/k32w0/k32w061/README.md) (commit id :: https://github.com/openthread/ot-nxp/commit/f8d5376ef1e958d2e59f4afa2587a1dbdf092c6f)

I am running otbr-agent on the ubuntu(**v22.02**) PC using the following command from ot-br-posix GitHub (https://openthread.io/guides/border-router) (commit id :: 495612f696947fc38dc71e8ee3378477378cf144 )

I have used the main branch from the repo for the otbr-agent and RCP image.

#/usr/sbin/otbr-agent -I wpan0 -B enp1s0 spinel+hdlc+uart:///dev/ttyUSB0 trel://enp1s0

The otbr-agent is successfully running on Ubuntu, but the **wpan0** interface is not created automatically. Please help with this issue as well.

But the otbr-agent is failing to communicate with the K32W dongle and giving the following error.

otbr-agent[33585]: [NOTE]-AGENT---: Running 0.3.0-1612526196
otbr-agent[33585]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[33585]: [NOTE]-AGENT---: Thread interface: enp1s0
otbr-agent[33585]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0
otbr-agent[33585]: [NOTE]-AGENT---: Radio URL: trel://enp1s0
otbr-agent[33585]: [NOTE]-ILS-----: Infra link selected: enp1s0
otbr-agent[33585]: [INFO]-NCP-----: OpenThread log level changed to 4
otbr-agent[33585]: 49d.18:56:15.522 [W] Platform------: Wait for response timeout
otbr-agent[33585]: 49d.18:56:15.523 [I] Platform------: Software reset RCP successfully
otbr-agent[33585]: 49d.18:56:17.525 [W] Platform------: Wait for response timeout
otbr-agent[33585]: 49d.18:56:17.525 [C] Platform------: **HandleRcpTimeout() at radio_spinel_impl.hpp:2301: RadioSpinelNoResponse**
systemd[1]: otbr-agent.service: Main process exited, code=exited, status=6/NOTCONFIGURED
systemd[1]: otbr-agent.service: Failed with result 'exit-code'.
systemd[1]: otbr-agent.service: Scheduled restart job, restart counter is at 677.
systemd[1]: Stopped OpenThread Border Router Agent.
systemd[1]: Starting OpenThread Border Router Agent...
systemd[1]: Started OpenThread Border Router Agent.
otbr-agent: [NOTE]-AGENT---: Backbone interface: enp1s0

Would you like me to make specific changes to communicate over USB for the dongle?

is there any ready example for an open thread RCP Image present for k32w?

**Comment by jwhui** [comment] 2023-05-03 19:55
Duplicate of: https://github.com/openthread/ot-nxp/issues/491

**Closed by jwhui** 2023-05-03 19:55 UTC
