### ISSUE TITLE
Child Supervision disable meaning

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#363] opened 2020-01-16 08:31 UTC
In openthread stack, by default child supervision is disabled.
So how or when does mtd re-attach in case child supervison is disabled and it gets detached from router.

**Comment by jwhui** [comment] 2020-01-16 17:46
Duplicate of https://github.com/openthread/openthread/issues/4479

**Closed by jwhui** 2020-01-16 17:46 UTC
