### ISSUE TITLE
wpantund.service is not listed as an enabled service during Step 4 of the "Build and Configuration" page  

### ISSUE THREAD

**Issue by bsvean2** [openthread/ot-br-posix#292] opened 2019-05-21 03:25 UTC
I am trying to use a Rapsberry Pi 3B+ to set up an OTBR to be used with a CC26x2R Wireless MCU LaunchPad as an NCP (CC2652 platform). I am following the instructions from https://openthread.io/guides/border-router/build. wpantund.service is not listed as an enabled service during Step 4 of the "Build and Configuration" page. I used the "sudo systemctl status" command to verify that the all of the required services are running, and wpantund.service is not listed as one of them. The other three services are listed (avahi-daemon.service, otbr-agent.service, otbr-web.service). This is preventing me from moving forward with the "Build and Configuration" page.

**Comment by jwhui** [comment] 2019-05-21 03:34
@bsvean2, can you verify that `Config:NCP:SocketPath` in `/etc/wpantund.conf` is configured properly for your NCP?

**Comment by bsvean2** [comment] 2019-05-21 03:52
@jwhui To do this, I went into the script located at /ot-br-posix/script/_wpantund and I changed the line "'/Config:NCP:SocketPath "\/dev/i Config:NCP:SocketPath "/dev/ttyUSB0"' to "'/Config:NCP:SocketPath "\/dev/i Config:NCP:SocketPath "/dev/ttyACM0" This is the port that my NCP is on.

Is this the correct way to do that?

**Comment by jwhui** [comment] 2019-05-21 04:15
@bsvean2, you can edit `script/_wpantund` before running the build/install script ( i.e. `./script/setup`), that is one way to do it. You could have also edited `/etc/wpantund.conf` directly after installation, as suggested by the [Build and Configuration](https://openthread.io/guides/border-router/build) guide.

As mentioned earlier, can you validate that `Config:NCP:SocketPath` in `/etc/wpantund.conf` is configured properly?

If the configuration checks out, can you trying calling `sudo service wpantund restart` and providing both the console and syslog output?

**Comment by bsvean2** [comment] 2019-05-21 05:09
@jwhui `Config:NCP:SocketPath` in `/etc/wpantund.conf` is now configured properly. I changed it to:
`Config:NCP:SocketPath "/dev/ttyACM0"`

I just now realized that you can access `/etc/wpantund.conf` using `sudo nano /etc/wpantund.conf`

I now see wpantund.service as an enabled service, although, now I can not form a network using the Web GUI. I get a message saying "Form operation has failed"

**Comment by jwhui** [comment] 2019-05-21 05:11
It may be that the NCP already has a network configuration. You can try to leave the network first.

Can you provide the output of `sudo wpanctl status`?

**Comment by bsvean2** [comment] 2019-05-21 05:17
Sure. It is:
```
wpan0 => [
	"NCP:State" => "offline"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20180926-00374-g74942164; CC2652; Feb 10 2019 12:47:28"
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA154E5]
]
```

**Comment by jwhui** [comment] 2019-05-21 05:19
Can you try:
```
$ sudo wpanctl leave
$ sudo wpanctl form -T2 OpenThread
```

**Comment by bsvean2** [comment] 2019-05-21 05:24
```
$ sudo wpanctl status
wpan0 => [
	"NCP:State" => "offline"
	"Daemon:Enabled" => true
	"NCP:Version" => "OPENTHREAD/20180926-00374-g74942164; CC2652; Feb 10 2019 12:47:28"
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA154E5]
]
$ sudo wpanctl leave
Leaving current WPAN. . .
$ sudo wpanctl form -T2 OpenThread
Forming WPAN "OpenThread" as node type "router"
form: error: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
$ sudo wpanctl status
wpan0 => [
	"NCP:State" => "uninitialized:fault"
	"Daemon:Enabled" => true
	"NCP:Version" => ""
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA154E5]
]
```

**Comment by jwhui** [comment] 2019-05-21 16:00
It seems there may be an issue with the NCP.

@srickardti, any thoughts?

**Comment by srickardti** [comment] 2019-05-21 17:51
I'll build a Border Router and NCP from the repo here in a bit to make sure that they work together.

@bsvean2, can you check that you have a Rev E of the silicon (https://e2e.ti.com/support/wireless-connectivity/bluetooth/f/538/t/767769). Also do you have atleast a 2.5 mA power source supplying the RasPi? The EnergyTrace circuit in the debugger is pretty power hungry.

If that is all working, download the TI SDK (http://www.ti.com/tool/simplelink-cc13x2-26x2-sdk) and try out the ncp_ftd example. It will be a drop in replacement for the one built from the OpenThread repo. I know the SDK examples will run with the border router.

**Comment by srickardti** [comment] 2019-05-22 00:06
Just got a BeagleBone Black Border Router up and running with the SIMPLELINK-CC13X2-26X2-SDK_3.10.00.53. But trying a basic scan with the ncp_ftd from the OpenThread repository fails.

I don't have time today to look into this, but I've got a setup to debug it. I'm pretty sure I know where it is running into an issue. Sorry for the difficulty, we touch our SDK more often than the upstream repository.

**Comment by bsvean2** [comment] 2019-05-26 19:52
Update on this...
I have the Rev E of the silicon.
I am able to form a Thread Network using the SIMPLELINK-CC13X2-26X2-SDK_3.10.00.53 ncp_ftd example.

```
$ sudo wpanctl leave
Leaving current WPAN. . .
$ sudo wpanctl status
wpan0 => [
	"NCP:State" => "offline"
	"Daemon:Enabled" => true
	"NCP:Version" => "TI-OPENTHREAD/1.2.4.0; CC2652; May 26 2019 14:22:40"
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA158B4]
]
$ sudo wpanctl leave
Leaving current WPAN. . .
$ sudo wpanctl form -T2 OpenThread
Forming WPAN "OpenThread" as node type "router"
Successfully formed!
$ sudo wpanctl status
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "TI-OPENTHREAD/1.2.4.0; CC2652; May 26 2019 14:22:40"
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA158B4]
	"NCP:Channel" => 11
	"Network:NodeType" => "leader"
	"Network:Name" => "OpenThread"
	"Network:XPANID" => 0xF782EFAE44C26424
	"Network:PANID" => 0x2FF5
	"IPv6:LinkLocalAddress" => "fe80::7c2a:1610:f343:5d07"
	"IPv6:MeshLocalAddress" => "fdf7:82ef:ae44:0:e3eb:79fb:fc6a:aba5"
	"IPv6:MeshLocalPrefix" => "fdf7:82ef:ae44::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]
```
I was also able to form a network using the web GUI, and got the following status result:
```
$ sudo wpanctl status
wpan0 => [
	"NCP:State" => "associated"
	"Daemon:Enabled" => true
	"NCP:Version" => "TI-OPENTHREAD/1.2.4.0; CC2652; May 26 2019 14:22:40"
	"Daemon:Version" => "0.08.00d (/f5de4e6; May 20 2019 19:24:45)"
	"Config:NCP:DriverName" => "spinel"
	"NCP:HardwareAddress" => [00124B001CA158B4]
	"NCP:Channel" => 15
	"Network:NodeType" => "leader"
	"Network:Name" => "OpenThreadGuide"
	"Network:XPANID" => 0xDEAD1111DEAD2222
	"Network:PANID" => 0xDEAD
	"IPv6:LinkLocalAddress" => "fe80::2c47:bba7:db66:1e40"
	"IPv6:MeshLocalAddress" => "fdde:ad11:11de:0:595c:2640:9ea0:95d"
	"IPv6:MeshLocalPrefix" => "fdde:ad11:11de::/64"
	"com.nestlabs.internal:Network:AllowingJoin" => false
]
```

**Comment by srickardti** [comment] 2019-05-29 14:32
I believe the issue is the change in Radio ROM for the release version of the silicon. I'm currently working on back-porting the changes we did for the Rev E silicon.

Good to hear you've got a working setup right now.

**Comment by srickardti** [comment] 2019-05-30 23:11
I've updated the driverlib used by OpenThread here: https://github.com/srickardti/openthread/tree/19q2-update-driverlib. That seems to get us past the hard fault because of the radio ROM, but the border router gets into a loop trying to associate. The device promotes to a leader but fails this requirement. Is the NCP configured correctly for the ot-br with it's default configuration?

```
Oct  7 16:41:32 beaglebone wpantund[1313]: wpantund[1313]: SpinelNCPTaskSendCommand.cpp:323: Requirement Failed ((mRetVal == kWPANTUNDStatus_Ok) || (mRetVal == kWPANTUNDStatus_Busy))
Oct  7 16:41:32 beaglebone wpantund[1313]: wpantund[1313]: SendCommand task encountered an error: 16 (0x00000010)
Oct  7 16:41:32 beaglebone wpantund[1313]: wpantund[1313]: SpinelNCPTaskSendCommand.cpp:381: Check Failed (error 16)
Oct  7 16:41:32 beaglebone wpantund[1313]: wpantund[1313]: Error PropertyNotFound (16) while performing "adding on-mesh prefix" on NCP - Resetting NCP.
```

**Comment by jwhui** [comment] 2019-05-30 23:15
@srickardti, it seems your NCP may be missing the `BORDER_ROUTER=1` build option.

Make sure to include the following build options when building the NCP image:
```
BORDER_AGENT=1 BORDER_ROUTER=1 COMMISSIONER=1 UDP_FORWARD=1
```

**Comment by srickardti** [comment] 2019-05-31 19:11
Yep, that was it. It's been a while since I've built an NCP from the upstream repository.

The border router works with this OpenThread pull request: https://github.com/openthread/openthread/pull/3888

**Comment by jwhui** [comment] 2019-06-07 17:54
Resolved by https://github.com/openthread/openthread/pull/3888.

**Closed by jwhui** 2019-06-07 17:54 UTC
Labels: question
