### ISSUE TITLE
Clean build gives Failed to start dhcp6_pd_daemon.service: Unit otbr-agent.service not found

### ISSUE THREAD

**Issue by pac8086** [openthread/ot-br-posix#2608] opened 2024-11-19 21:17 UTC
**Describe the bug** A clear and concise description of what the bug is.
First time clean build fails  
I believe recent change to script/_dhcpv6_pd_ref causes the issue
commit 094d0ccf2f95aca07ff5a1a9d5fafde5a02a3c3e 

**To Reproduce** Information to reproduce the behavior, including:
From a clean system (e.g RPI)  which has never built otbr
Connect Wi-Fi interface using raspi-config.
sudo apt-get update
sudo apt-get install git
git clone https://github.com/openthread/ot-br-posix
cd ot-br-posix
./script/bootstrap
INFRA_IF_NAME=wlan0 ./script/setup
fails (see below)

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.
Build completes

**Console/log output** If applicable, add console/log output to help explain your problem.
[Install]
WantedBy=multi-user.target
have systemctl
command -v systemctl
sudo systemctl daemon-reload
sudo systemctl enable dhcp6_pd_daemon.service
Created symlink /etc/systemd/system/multi-user.target.wants/dhcp6_pd_daemon.service → /etc/systemd/system/dhcp6_pd_daemon.service.
sudo systemctl start dhcp6_pd_daemon.service
Failed to start dhcp6_pd_daemon.service: Unit otbr-agent.service not found.

**Additional context** Add any other context about the problem here.
On a clean system otbr-agent does not exist at this stage.

**Comment by yangsong-cnyn** [comment] 2024-11-20 03:47
Hi @pac8086 , the issue is because I changed the default Raspi config incorrectly to include what should only be enabled in reference device. I will let you know once fix is merged.

**Comment by Exormeter** [comment] 2024-11-20 12:30
Same issue here, is there a workaround like checking out an older commit?

**Closed** 2024-11-20 15:14 UTC
