### ISSUE TITLE
The frame count value of the link layer of the TBR changes unexpectedly.

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/ot-br-posix#2482] opened 2024-09-10 07:16 UTC
**Describe the bug** A clear and concise description of what the bug is.
Normally, the frame count at the link layer of an outgoing packet should increase only. From the capture of packets, the frame count value will change randomly. 

The packets of Sniffer_00004_20240909080000_00000_20240909080011.pcapng
Frame 210273 -> 210399:   256 ->  1256
Frame 219115 -> 219218:  5743 ->  6744
Frame 233260 -> 233469: 10857 -> 11857
**Frame 498721 -> 499047: 27633 ->  1737**
The packets of Sniffer_00004_20240909080000_00001_20240909160653.pcapng
**Frame 170491 -> 171713: 4973 ->  2595**
Frame 181418 -> 181879: 2663 ->  3663
**Frame 186960 -> 187946: 3711 ->  2693**
**Frame 203442 -> 204144: 2809 ->  2767**
Frame 227400 -> 228364: 2874 ->  3874
**Frame 251150 -> 252659: 3999 ->  2969**
Frame 264497 -> 264724: 3368 ->  27637
**Frame 284917 -> 285116: 27833 ->  3133**
Frame 360593 -> 361656: 3536 ->  4536
**Frame 378225 -> 379158: 4615 ->  3627**
Frame 479837 -> 481744: 4107 ->  5107
![1](https://github.com/user-attachments/assets/02f65cc2-cf61-433a-9d90-f74eacf78d15)

![2](https://github.com/user-attachments/assets/96177b42-3163-41f3-acdd-2142e4077065)

![3](https://github.com/user-attachments/assets/edf57502-a1f8-480f-b773-1fa3de853f76)

![4](https://github.com/user-attachments/assets/5c50552a-90f2-430e-a97c-57db19d5006d)

![5](https://github.com/user-attachments/assets/04023137-990e-4d4a-9ef7-96710a573e47)

![6](https://github.com/user-attachments/assets/151bbb1d-dd6d-4e33-98bb-2835194b6e19)

![7](https://github.com/user-attachments/assets/0c815b5a-a2f6-4312-813d-234d034bc80a)

![8](https://github.com/user-attachments/assets/738f2ff8-0756-45cf-a4e0-18e7d0e6468c)

![9](https://github.com/user-attachments/assets/ad7a6f2f-1c5b-49e7-a0f1-0cea7522c20c)

![10](https://github.com/user-attachments/assets/1d888f66-59df-4396-acc4-41c31fb690ca)

![11](https://github.com/user-attachments/assets/112e1bf4-73c1-4b0b-a30c-0a97547407c8)

![12](https://github.com/user-attachments/assets/72747516-ab6c-4c5b-9f32-2c2dd1f0f215)

![13](https://github.com/user-attachments/assets/83eae042-e77b-4a42-a25f-724528813cb3)

![14](https://github.com/user-attachments/assets/6da7b1fc-ee11-456b-a030-1893c6fb6a9b)

![15](https://github.com/user-attachments/assets/5154a6cb-6164-4f76-ab49-a8810f3b199e)

**Comment by jinpeng1989** [comment] 2024-09-10 07:18
Network key: 20358d714e6344bce360d875089a0cf1
RLOC16 of TBR: wpan.src16 == 0xf400

[Sniffer_00004_20240909080000_00000_20240909080011.zip](https://github.com/user-attachments/files/16940931/Sniffer_00004_20240909080000_00000_20240909080011.zip)

[Sniffer_00004_20240909080000_00001_20240909160653.zip](https://github.com/user-attachments/files/16940934/Sniffer_00004_20240909080000_00001_20240909160653.zip)

[Sniffer_00004_20240909080000_00002_20240910065541.zip](https://github.com/user-attachments/files/16940938/Sniffer_00004_20240909080000_00002_20240910065541.zip)

**Comment by jinpeng1989** [comment] 2024-09-10 07:40
Once the frame count value becomes smaller, the encrypted packet of the Mac layer sent by the TBR will be dropped by the neighbor device. This issue comes up frequently. It can take hours or days for the network to return to normal. Because the frame count value needs to increase to the previous frame count maximum. Then the neighboring device will accept the new packet.

**Comment by jinpeng1989** [comment] 2024-09-10 09:13
I check another set of test scenarios, 1 TBR + 1 SED. The frame count value did not decrease, but it suddenly increased by 1000 on three occasions. Increasing by 1,000 doesn't seem random. It's more like design. In what case add 1000 instead of 1?
Frame  27048 ->  27085: 16054 ->  17054
Frame  31368 ->  31408: 18969 ->  19969
Frame  33708 ->  33788: 10857 ->  21974
![21](https://github.com/user-attachments/assets/75a6f52a-bc60-4c3f-bc4b-35866adea044)
![22](https://github.com/user-attachments/assets/c5d3d750-a7ed-492e-babf-01dbbfa35a5b)
![23](https://github.com/user-attachments/assets/093654d7-a7af-4610-b7f8-12192b366b98)

**Comment by jwhui** [comment] 2024-09-10 18:02
In most cases, the radio driver itself increments the MAC Frame Counter. Typically, OT will only set the MAC Frame Counter when the process is starting or when recovering from an unexpected RCP reset.

There was a bug related to RCP restoration that was recently fixed:
- https://github.com/openthread/openthread/pull/10635

However, if RCP restoration is getting invoked frequently, this would indicate that the RCP is resetting unexpectedly and the root cause of those reset failures should be found. RCP restoration is just sweeping the underlying bug under the covers. One way to really make obvious whether unexpected RCP resets is causing issues is by disabling the RCP restoration feature by setting the following to `0` at build time:
```
OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT
```

**Comment by jinpeng1989** [comment] 2024-09-11 03:01
![image](https://github.com/user-attachments/assets/707d1bad-2545-49a7-82b0-6f3bc25b42be)

**Comment by jwhui** [comment] 2024-09-11 14:30
Yes, I suggest resolving the frequent RCP failures.

**Comment by jinpeng1989** [comment] 2024-09-12 09:14
Reproduced the issue again, the otbr-agent log is set to debug. The log is attached. It may be helpful to analyze this issue.
[RCP_failure detected_2024-09-12.zip](https://github.com/user-attachments/files/16976534/RCP_failure.detected_2024-09-12.zip)

**Comment by jwhui** [comment] 2024-09-13 00:04
All of the failures are due to:
```
otbr-agent[31734]: 00:03:55.361 [W] P-RadioSpinel-: radio tx timeout
```
This indicates that the radio driver is not responding to the TX request in a timely manner.

**Comment by jinpeng1989** [comment] 2024-09-19 03:44
It is worth mentioning that when switching back to [GSDK 4.4.3](https://github.com/SiliconLabs/gecko_sdk/releases/tag/v4.4.3). After a week of testing, the "RCP failure detected" issue did not reproduced. This issue is easily reproduced in the Simplicity SDK, so it can be basically concluded. GSDK 4.3.3 does not have this issue.

**Comment by jwhui** [comment] 2024-09-19 20:48
Thanks for the update. Feel free to close this issue if it's resolved.

**Closed** 2024-09-20 06:04 UTC
