### ISSUE TITLE
Pre built Border Router image out of step with documentation

### ISSUE THREAD

**Issue by firehills** [openthread/ot-br-posix#501] opened 2020-07-01 08:57 UTC
At time of writing documentation at https://openthread.io/guides/border-router/docker/run suggests starting the docker container with 

docker run --sysctl "net.ipv6.conf.all.disable_ipv6=0 \
        net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" \
        -p 8080:80 --dns=127.0.0.1 -it --volume \
        /dev/ttyACM0:/dev/ttyACM0 --privileged openthread/otbr \
        --radio-url spinel+hdlc+uart:///dev/ttyACM0

This is ok for those who have built their own image, however for anyone starting out using the guide and the "pre built" image via

"docker pull openthread/otbr:latest" 

As listed on https://openthread.io/guides/border-router/docker , the --radio-url is not yet supported. 

For the pre built image, docker_entrypoint.sh still uses the older style --ncp-path

function parse_args()
{
    while [ $# -gt 0 ]
    do
        echo $1
        case $1 in
        --ncp-path)
            NCP_PATH=$2
            shift
            shift
            ;;

I think the fix would be to update the pre built image,  (it has been 16 months?) 

$docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
openthread/otbr     latest              e7f23b10eb7b        16 months ago       1.32GB

Thanks in advance

**Comment by bukepo** [comment] 2020-07-01 09:24
@jwhui is it possible to automatically update the latest tag automatically?

**Comment by jwhui** [comment] 2020-07-01 17:59
This is a duplicate of #452. I'll take a look an implementing that.

**Closed** 2020-07-16 18:55 UTC
Labels: continuous-integration
