### ISSUE TITLE
ot-br-posix as an on-mesh commissioner fails to accept client hello packets

### ISSUE THREAD

**Issue by JaneFromSilabs** [openthread/ot-br-posix#561] opened 2020-09-16 19:05 UTC
OOB connections are still working for me, as are DTLS connections soc-to-soc, however the case of soc to BR using DTLS psk is giving me problems.  I did have this working previously so this did work before.  Originally we had thought this was a thread 1.2/1.1 incompatibility issue but we found that 1.1 images also aren't connecting properly.

Here is my BR console for one of the various tests I ran:
```
sudo ot-ctl factoryreset
sleep 3
sudo ot-ctl channel 11
Done
sudo ot-ctl panid 0xdf47
Done
sudo ot-ctl networkname R0GUE7
Done
sudo ot-ctl masterkey 00112233445566778899aabbccddeeff
Done
sudo ot-ctl extpanid 000df47000000000
Done
sudo ot-ctl pskc -p S1LABS6
Done
sudo ot-ctl ifconfig up
Done
sudo ot-ctl thread start
Done
pi@rpi1:~ $ sudo ot-ctl
> commissioner start
Commissioner: petitioning
Done
> Commissioner: active

>
> commissioner joiner add * S1LABS6
Done
> Commissioner: Joiner remove
```

And soc console:
```
> factoryreset
channel 11
Done
>
> panid 0xdf47
Done
>
> ifconfig up
Done
>
> joiner start S1LABS6
Done
>
> Join failed [Security]
```

Version information:
```
pi@rpi1:~/ot-br-posix $ git show
commit 274c11a371df6ffe0f7562359f31dd43af0fe871
Author: Jiacheng Guo <gjc@google.com>
Date:   Fri Sep 11 23:45:04 2020 +0800
```
```
> version
SL-OPENTHREAD/1.1.0.0 GitHub-babb66d9c; EFR32; Sep 14 2020 22:01:04
Done
```
I would attach the actual trace file but the format isn't supported here and the tool I used was Silabs Simplicity Studio which you may not have installed.  But here is a picture so you can see the point of failure:
![image](https://user-images.githubusercontent.com/58004715/93380170-dee4af80-f82c-11ea-8c67-966356a83561.png)

I'm using 2x brd4161a but I don't think that matters.  My topology is just the simple 2 node network BR to SoC.

Please let me know if I've done something incorrectly and/or what other information I can provide.  Thanks.

**Comment by gjc13** [comment] 2020-09-21 03:08
The command line output showed that the joiner has been removed. This can caused by timeout or another joiner already joined. You need to launch the joiner before you see the line  `Commissioner: Joiner remove`.

**Comment by JaneFromSilabs** [comment] 2020-09-21 12:43
There are no other joiners and you can see I'm factory resetting prior.  This addition is happening very quick and should not be timing out.  This used to work previously (in automation) and is now failing (in automation as well as manually).  Did the timeout value change?

**Comment by JaneFromSilabs** [comment] 2020-09-22 15:40
Looking at this again today and it is clear to me that this is not a timeout issue.  Something here has changed and is no longer working as it should.

**Comment by gjc13** [comment] 2020-09-23 02:25
I cannot reproduce this issue. Can you provide the cmake options you're using and the otbr log?

You can acquire the log by `cat /var/log/syslog | grep otbr`

**Comment by JaneFromSilabs** [comment] 2020-10-05 20:12
Sorry for the delay.  I updated to the latest available and now I can get this working manually, but for some reason (timing?) the automated case that used to work, now consistently fails.  

These are the commands sent both in automation and manually (201 is the otbr, 221 is the soc):
```<172.16.1.201> issuing cmd<channel 11> 
<172.16.1.201> issuing cmd<networkname R0GUE1> 
<172.16.1.201> issuing cmd<panid 0xDF46> 
<172.16.1.201> issuing cmd<extpanid 000df46000000000> 
<172.16.1.201> issuing cmd<masterkey 00112233445566778899AABBCCDD4161> 
<172.16.1.201> issuing cmd<pskc -p 3c72b2a2cd7cb42bcf927c147bdfd34c> 
<172.16.1.201> issuing cmd<ifconfig up> 
<172.16.1.201> issuing cmd<thread start> 
<172.16.1.201> issuing cmd<prefix add fdde:ad00:dead:beef::/64 paros med> 
<172.16.1.201> issuing cmd<prefix add fdde:ad03::/64 paros med> 
<172.16.1.201> issuing cmd<prefix add 2001:22::/64 paros med> 
<172.16.1.201> issuing cmd<commissioner start> 

<172.16.1.221> issuing cmd<eui64> 

<172.16.1.201> issuing cmd<commissioner joiner add 000d6ffffece275b S1LABS6> 

<172.16.1.221> issuing cmd<channel 11> 
<172.16.1.221> issuing cmd<panid 0xDF46> 
<172.16.1.221> issuing cmd<ifconfig up> 
<172.16.1.221> issuing cmd<joiner start S1LABS6> 
```

Here are the syslog messages I get when this fails in automation:

```
Oct  5 21:01:51 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send delayed message (fe80:0:0:0:bc67:b92b:b124:9340)
Oct  5 21:01:51 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:100, chksum:6868, to:be67b92bb1249340, sec:no, prio:net
Oct  5 21:01:51 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:01:51 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[fe80:0:0:0:bc67:b92b:b124:9340]:19788
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:473, chksum:aaba, sec:no, error:ReassemblyTimeout, prio:low, rss:-31.0
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     src:[fe80:0:0:0:a01b:e18f:85ae:5eb7]:1000
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     dst:[fe80:0:0:0:4e2:9082:45ee:e22c]:1000
Oct  5 21:02:06 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:473, chksum:a9ba, sec:no, error:ReassemblyTimeout, prio:low, rss:-31.0
Oct  5 21:02:06 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     src:[fe80:0:0:0:a01b:e18f:85ae:5eb7]:1000
Oct  5 21:02:06 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     dst:[fe80:0:0:0:4e2:9082:45ee:e22c]:1000
Oct  5 21:02:07 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
Oct  5 21:02:07 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:90, chksum:96ee, to:0xffff, sec:no, prio:net
Oct  5 21:02:07 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:02:07 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
Oct  5 21:02:08 rpi1 otbr-agent[3019]: [INFO]-PLAT----: processNetifLinkEvent: OK
Oct  5 21:02:08 rpi1 wpa_supplicant[439]: wlan0: Failed to initiate sched scan
Oct  5 21:02:11 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive
Oct  5 21:02:11 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received keep alive
Oct  5 21:02:11 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive response
Oct  5 21:02:11 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received Leader keep-alive response
Oct  5 21:02:23 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:473, chksum:a8ba, sec:no, error:ReassemblyTimeout, prio:low, rss:-31.0
Oct  5 21:02:23 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     src:[fe80:0:0:0:a01b:e18f:85ae:5eb7]:1000
Oct  5 21:02:23 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     dst:[fe80:0:0:0:4e2:9082:45ee:e22c]:1000
Oct  5 21:02:30 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
Oct  5 21:02:30 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:90, chksum:e567, to:0xffff, sec:no, prio:net
Oct  5 21:02:30 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:02:30 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
Oct  5 21:02:36 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive
Oct  5 21:02:36 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received keep alive
Oct  5 21:02:36 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive response
Oct  5 21:02:36 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received Leader keep-alive response
Oct  5 21:02:55 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:473, chksum:a7ba, sec:no, error:ReassemblyTimeout, prio:low, rss:-31.0
Oct  5 21:02:55 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     src:[fe80:0:0:0:a01b:e18f:85ae:5eb7]:1000
Oct  5 21:02:55 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     dst:[fe80:0:0:0:4e2:9082:45ee:e22c]:1000
Oct  5 21:03:01 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive
Oct  5 21:03:01 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received keep alive
Oct  5 21:03:01 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive response
Oct  5 21:03:01 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received Leader keep-alive response
Oct  5 21:03:08 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
Oct  5 21:03:08 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:90, chksum:777d, to:0xffff, sec:no, prio:net
Oct  5 21:03:08 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:03:08 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
Oct  5 21:03:11 rpi1 otbr-agent[3019]: [INFO]-PLAT----: processNetifLinkEvent: OK
Oct  5 21:03:11 rpi1 wpa_supplicant[439]: wlan0: Failed to initiate sched scan
Oct  5 21:03:26 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive
Oct  5 21:03:26 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received keep alive
Oct  5 21:03:26 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive response
Oct  5 21:03:26 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received Leader keep-alive response
Oct  5 21:03:36 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send Advertisement (ff02:0:0:0:0:0:0:1)
Oct  5 21:03:36 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:90, chksum:cb60, to:0xffff, sec:no, prio:net
Oct  5 21:03:36 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:03:36 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent MGMT_COMMISSIONER_SET.req to leader
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: Removed Joiner (eui64:000d6ffffece275b, S1LABS6)
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent commissioning dataset set response
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-CORE----: Notifier: StateChanged (0x00000200) [NetData]
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MLE-----: Send Data Response (ff02:0:0:0:0:0:0:1)
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-IP6-----: Removed unsecure port 1000
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received MGMT_COMMISSIONER_SET response
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MAC-----: Sent IPv6 UDP msg, len:184, chksum:d0e3, to:0xffff, sec:yes, prio:net
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     src:[fe80:0:0:0:4e2:9082:45ee:e22c]:19788
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MAC-----:     dst:[ff02:0:0:0:0:0:0:1]:19788
Oct  5 21:03:51 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive
Oct  5 21:03:51 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received keep alive
Oct  5 21:03:51 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent keep alive response
Oct  5 21:03:51 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: received Leader keep-alive response
Oct  5 21:03:53 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping rx lowpan HC frame, error:Drop, len:25, src:a21be18f85ae5eb7, dst:06e2908245eee22c, sec:no
```

**Comment by librasungirl** [comment] 2020-10-09 05:02
The log shows that the DTLS client hello packet is always dropped due to `error:ReassemblyTimeout` and finally the commissioner will remove the joiner after the default timeout (~120s).
```
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----: Dropping (reassembly queue) IPv6 UDP msg, len:473, chksum:aaba, sec:no, error:ReassemblyTimeout, prio:low, rss:-31.0
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     src:[fe80:0:0:0:a01b:e18f:85ae:5eb7]:1000
Oct  5 21:01:58 rpi1 otbr-agent[3019]: [NOTE]-MAC-----:     dst:[fe80:0:0:0:4e2:9082:45ee:e22c]:1000
...
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: sent MGMT_COMMISSIONER_SET.req to leader
Oct  5 21:03:47 rpi1 otbr-agent[3019]: [INFO]-MESH-CP-: Removed Joiner (eui64:000d6ffffece275b, S1LABS6)
```

We know that the large DTLS client hello packet is fragmented during transmission over 15.4 radio, and the default reassembly timeout between fragments is 2s.
[```#define OPENTHREAD_CONFIG_6LOWPAN_REASSEMBLY_TIMEOUT 2```](https://github.com/openthread/openthread/blob/00f3043a066c28215a65bee0c427b6f36f171fe0/src/core/config/openthread-core-default-config.h#L183-L190)

Is it the same testbed when testing manually and automatically? Is it possible that there are some interference for the automatic testbed?

**Comment by JaneFromSilabs** [comment] 2020-10-09 17:19
Thank you for that information.  This is the same test bed in all of these test runs.  It is a test bed in my home, so I wouldn't think there would be a lot of interference.  Since this is working for me manually, I'm closing this.  If I find the cause of the automated test failure, I will reopen.  Thanks again, @gjc13 and @librasungirl

**Comment by librasungirl** [comment] 2020-10-10 09:53
@JaneFromSilabs 
Fyi, there is one similar `error:ReassemblyTimeout` issue on nRF platform which could be resolved by improving the baudrate (see https://groups.google.com/g/openthread-users/c/t08i-B6Iqwo/m/ZCMQtc34DAAJ)

Not sure but I am thinking you may have a try to see if it helps.

**Comment by JaneFromSilabs** [comment] 2020-10-12 12:34
@librasungirl Thanks, I'll look into it!

**Comment by JaneFromSilabs** [comment] 2020-10-16 14:24
I need to reopen this and I have a bit more information.  This problem seems to be intermittent.  I can both pass and fail DTLS authentication manually as well as in my automated test.  Increasing the baud rate definitely helps but the problem can still be replicated with enough repetition.  Additionally, I went back to test against older builds from a few months back and the problem exists there as well in the latest code.  The common point here is always a number of these syslog messages in both the passing and failing cases:
Dropping (reassembly queue) IPv6 UDP msg, len:513, chksum:5c72, sec:no, error:ReassemblyTimeout, prio:normal, rss:-21.0

I suspect that the retry code is allowing this process to succeed occasionally but the basic problem seems to persist regardless.  Can you please check on your side and see if you are getting these syslog messages even in passing cases?  Thank you!

**Comment by JaneFromSilabs** [comment] 2020-10-19 13:40
Also, 2 other people here have reported the same problem.  I'm not sure where this problem lives but it is definitely not limited to my test bed.

**Comment by librasungirl** [comment] 2020-10-20 07:08
Hi Jane

May I know the baudrate you are using when the issue still exists with `enough repetition`? 

Would you please check whether or not adjusting spinel frame buffer size for rcp could help?
e.x., 
`typedef Hdlc::MultiFrameBuffer<kMaxFrameSize> RxFrameBuffer;` 
->
`typedef Hdlc::MultiFrameBuffer<4096> RxFrameBuffer;`

**Comment by suveshpratapa** [comment] 2020-10-20 11:40
Hi @librasungirl, I'm an engineer at SiLabs also looking into this issue along with @JaneFromSilabs .

We tried upping the baud rate to 460800 as follows in `/etc/default/otbr-agent`:
`OTBR_AGENT_OPTS="-I wpan0 spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800"`

We verified the baud rate by running the following command:
```
pi@raspberrypi:~ $ stty -F /dev/ttyACM0 
speed 460800 baud; line = 0;
min = 1; time = 0;
-brkint -icrnl -imaxbel
-opost
-isig -icanon -iexten -echo

```

Additionally, I changed `kMaxSize` to `4096` in `third_party/openthread/repo/src/lib/spinel/spinel_interface.hpp` as you suggested above.

With both of these changes, it seems to help our use case.  However, there's some peculiar behavior I'm seeing, which I will explain below:

If you look at Jane's test setup above, it's a simple two device test.  A border router (also an on-mesh commissioner), and a joiner.  The border router starts the network and starts in on-mesh commissioner mode, then the joiner initiates the DTLS connection with client hello.

If I keep the border router up, i.e., don't reset it, then it seems I can retry the joiner connection over and over without hitches (but only with the above fixes.  Without the above fixes, the failures are manifested with the `error:ReassemblyTimeout` error)

However, if I issue `factoryreset` on the border router subsequently (this is part of Jane's testbed scripts) and retry the whole test, then the border router can get into a state where it will drop any incoming DTLS client hello.

This is manifested as the following type of error messages in the syslog.  This is an example of a set of client hello fragments, all dropped.

```
Oct 20 07:26:17 raspberrypi otbr-agent[1116]: [NOTE]-MAC-----: Dropping rx frag frame, error:Drop, len:97, src:d28f6fbd691a1a8c, dst:868cd0e06282c7b1, tag:19038, offset:0, dglen:473, sec:no
Oct 20 07:26:17 raspberrypi otbr-agent[1116]: [NOTE]-MAC-----: Dropping rx frag frame, error:Drop, len:96, src:d28f6fbd691a1a8c, dst:868cd0e06282c7b1, tag:19038, offset:136, dglen:473, sec:no
Oct 20 07:26:17 raspberrypi otbr-agent[1116]: [NOTE]-MAC-----: Dropping rx frag frame, error:Drop, len:96, src:d28f6fbd691a1a8c, dst:868cd0e06282c7b1, tag:19038, offset:232, dglen:473, sec:no
Oct 20 07:26:17 raspberrypi otbr-agent[1116]: [NOTE]-MAC-----: Dropping rx frag frame, error:Drop, len:96, src:d28f6fbd691a1a8c, dst:868cd0e06282c7b1, tag:19038, offset:328, dglen:473, sec:no
Oct 20 07:26:17 raspberrypi otbr-agent[1116]: [NOTE]-MAC-----: Dropping rx frag frame, error:Drop, len:49, src:d28f6fbd691a1a8c, dst:868cd0e06282c7b1, tag:19038, offset:424, dglen:473, sec:no
```

I debugged the code, adding some stderr prints, and noticed that this is because on these subsequent runs, the border router is not adding the unsecure joiner port (1000) after registering as a commissioner.  This seems to work the first time, but not any time after that after we do a factoryreset.  A reboot of the raspberry pi appears to fix the issue, I need to do more testing.

Code path:
`src/core/thread/mesh_forwarder.cpp:HandleFragment`
Fails during this step: `VerifyOrExit(Get<Ip6::Filter>().Accept(*message), error = OT_ERROR_DROP);`

Reason:
`src/core/net/ip6_filter.cpp:Filter::Accept`
Fails in this step:
```
    // Check against allowed unsecure port list
    for (uint16_t unsecurePort : mUnsecurePorts)
    {
        if (unsecurePort != 0 && unsecurePort == dstport)
        {
            ExitNow(rval = true);
        }
    }

```

Note:  All of this testing was done against current [HEAD](https://github.com/openthread/ot-br-posix/tree/6f0c803670096107c96a335d574e500de302600b) when I tested: `ot-br-posix` commit `6f0c803670096107c96a335d574e500de302600b`, `third_party/openthread/repo` commit `dc9b032dad4d348da389c1053457147dd2817bd8`

**Comment by librasungirl** [comment] 2020-10-21 01:46
Hi @suveshpratapa 

Yes, it looks like the unsecure port`:MJ` is not added.

Would you please help to share the full syslog since `factoryreset` is issued?

**Comment by suveshpratapa** [comment] 2020-10-21 09:41
Attached a text file with the full log capturing behavior of successful DTLS, followed by failure after factoryreset. The log corresponds to the test procedure on OTBR console as follows.  We are basically repeating the test after factoryreset.

```
# fresh state, to induce success
sudo reboot

channel 11
panid 0xFACE
masterkey 00112233445566778899AABBCCDDEEFF
ifconfig up
thread start

commissioner start
commissioner joiner add 000b57fffe25ffa2 ABCDEF
# successful dtls

factoryreset

channel 11
panid 0xFACE
masterkey 00112233445566778899AABBCCDDEEFF
ifconfig up
thread start

commissioner start
commissioner joiner add 000b57fffe25ffa2 ABCDEF
#failure in dtls due to missing unsecure port
```

In the attached log, the factoryreset above is issued around the time:
```
Oct 21 05:29:52 raspberrypi otbr-agent[1111]: [INFO]-CLI-----: execute command: factoryreset
```

For the successful case, when the joiner is added, we see:
```
Oct 21 05:29:05 raspberrypi otbr-agent[1111]: [INFO]-MESH-CP-: Added Joiner (eui64:000b57fffe25ffa2, ABCDEF)
Oct 21 05:29:05 raspberrypi otbr-agent[1111]: [INFO]-MESH-CP-: sent commissioning dataset set response
Oct 21 05:29:05 raspberrypi otbr-agent[1111]: [INFO]-CORE----: Notifier: StateChanged (0x00000200) [NetData]
Oct 21 05:29:05 raspberrypi otbr-agent[1111]: [INFO]-MLE-----: Send Data Response (ff02:0:0:0:0:0:0:1)
Oct 21 05:29:05 raspberrypi otbr-agent[1111]: [INFO]-IP6-----: Added unsecure port 1000
```

For the failed case, when the joiner is added, we see:
```
Oct 21 05:30:15 raspberrypi otbr-agent[1111]: [INFO]-MESH-CP-: Added Joiner (eui64:000b57fffe25ffa2, ABCDEF)
Oct 21 05:30:15 raspberrypi otbr-agent[1111]: [INFO]-MESH-CP-: sent commissioning dataset set response
Oct 21 05:30:15 raspberrypi otbr-agent[1111]: [INFO]-CORE----: Notifier: StateChanged (0x00000200) [NetData]
Oct 21 05:30:15 raspberrypi otbr-agent[1111]: [INFO]-MLE-----: Send Data Response (ff02:0:0:0:0:0:0:1)
```

Full log:
[dtls-success-followed-by-failure-after-factoryreset.txt](https://github.com/openthread/ot-br-posix/files/5414907/dtls-success-followed-by-failure-after-factoryreset.txt)

**Comment by librasungirl** [comment] 2020-10-22 05:41
Hi @suveshpratapa 
Thanks for the details. I can see the device catches the `NetData` change event, in theory the conditions for below `if` in [`JoinerRouter::Start()`](https://github.com/openthread/openthread/blob/ff76aac3db99c815045a549666137ee6a0723b2f/src/core/meshcop/joiner_router.cpp#L79-L88) should be satisfied already (otherwise there should be no further discover response or DTLS fragments).

```
    if (Get<NetworkData::Leader>().IsJoiningEnabled())
    {
        uint16_t port = GetJoinerUdpPort();


        VerifyOrExit(!mSocket.IsBound());


        IgnoreError(mSocket.Open(&JoinerRouter::HandleUdpReceive, this));
        IgnoreError(mSocket.Bind(port));
        IgnoreError(Get<Ip6::Filter>().AddUnsecurePort(port));
        otLogInfoMeshCoP("Joiner Router: start");
 }
```

So far, I may not have better suggestion other than adding debug log in `LeaderBase::IsJoiningEnabled()` and `JoinerRouter::Start()` to locate the reason for not adding the unsecure port.

**Comment by JaneFromSilabs** [comment] 2020-10-22 12:22
@librasungirl Could you please tell use whether or not you can reproduce this?  I don't think this should be a device specific issue but it would definitely be good information to know.  Thank you!

**Comment by suveshpratapa** [comment] 2020-10-22 23:12
Hi @librasungirl I have discovered the root cause of this issue.

After a successful DTLS join, i.e., after finishing Joiner Finalization, the commissioner removes the joiner / joiner UDP connection after a certain timeout.  However, if a factoryreset (or instance reset) is issued before this timeout, then, while closing the connection, the UDP socket has its socket handle cleared (because the DTLS connection is closed), but other state like mPort is not cleared.

After this, if a new connection is attempted again, the mSocket.IsBound() check fails below, and a valid unsecure port is not set.

```
src/core/meshcop/joiner_router.cpp:JoinerRouter::Start
    if (Get<NetworkData::Leader>().IsJoiningEnabled())
    {
        uint16_t port = GetJoinerUdpPort();

        VerifyOrExit(!mSocket.IsBound(), OT_NOOP);

        IgnoreError(mSocket.Open(&JoinerRouter::HandleUdpReceive, this));
        IgnoreError(mSocket.Bind(port));
        IgnoreError(Get<Ip6::Filter>().AddUnsecurePort(port));
        otLogInfoMeshCoP("Joiner Router: start");
    }
```

---

**Proposed fix that works for us:**

In src/core/net/udp6.cpp, when the socket is being closed:
```
otError Udp::Close(SocketHandle &aSocket)
{
    otError error = OT_ERROR_NONE;

#if OPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE
    error = otPlatUdpClose(&aSocket);
#endif
    SuccessOrExit(error);

    RemoveSocket(aSocket);
    aSocket.GetSockName().Clear();
    aSocket.GetPeerName().Clear();

exit:
    return error;
}

```

.. if otPlatUdpClose (for POSIX) returns an error, then the socket state is not cleared, and therefore the mPort value is not set to 0.

If a factoryreset is issued before the commissioner automatically removes the joiner, then otPlatUdpClose returns an error with OT_ERROR_INVALID_ARGS in the below definition:
```
otError otPlatUdpClose(otUdpSocket *aUdpSocket)
{
    otError error = OT_ERROR_NONE;
    int     fd;

    VerifyOrExit(aUdpSocket->mHandle != nullptr, error = OT_ERROR_INVALID_ARGS);
    fd = FdFromHandle(aUdpSocket->mHandle);
    VerifyOrExit(0 == close(fd), error = OT_ERROR_FAILED);

    aUdpSocket->mHandle = nullptr;

exit:
    return error;
}
```

*The following code change fixes this issue:*
```
diff --git a/src/posix/platform/udp.cpp b/src/posix/platform/udp.cpp
index ea46da18d..b9430e759 100644
--- a/src/posix/platform/udp.cpp
+++ b/src/posix/platform/udp.cpp
@@ -240,11 +240,12 @@ otError otPlatUdpClose(otUdpSocket *aUdpSocket)
     otError error = OT_ERROR_NONE;
     int     fd;
 
-    VerifyOrExit(aUdpSocket->mHandle != nullptr, error = OT_ERROR_INVALID_ARGS);
-    fd = FdFromHandle(aUdpSocket->mHandle);
-    VerifyOrExit(0 == close(fd), error = OT_ERROR_FAILED);
-
-    aUdpSocket->mHandle = nullptr;
+    if (aUdpSocket->mHandle != nullptr)
+    {
+        fd = FdFromHandle(aUdpSocket->mHandle);
+        VerifyOrExit(0 == close(fd), error = OT_ERROR_FAILED);
+        aUdpSocket->mHandle = nullptr;
+    }
 
 exit:
     return error;
```

**Comment by librasungirl** [comment] 2020-10-23 02:56
Hi @suveshpratapa 
Agree with your findings! Thanks for your investigation and your proposal looks good to me.  👍 

An equivalent patch is submitted to OpenThread Repo https://github.com/openthread/openthread/pull/5690. Please take a review.

**Comment by suveshpratapa** [comment] 2020-10-23 11:33
@librasungirl @jwhui 

Thank you for the prompt update and PR!

- The bug fix requires an ot-br-posix submodule pointer update for openthread as well.  I notice the pointer has not been updated for some time.  We can have our tests use the latest stack with this fix for now.

- Additionally, to resolve the timeout portion of this bug, we also had to increase the uart baud rate to 460800 and kMaxSize to 4096 in third_party/openthread/repo/src/lib/spinel/spinel_interface.hpp as you suggested above. I was going to ask if this value can be made configurable, but I notice this was already brought up in this issue: https://github.com/openthread/openthread/issues/5678 and a PR proposal is already in place: https://github.com/openthread/openthread/pull/5687 👍

**Closed** 2020-10-26 04:06 UTC
Labels: bug

**Comment by jwhui** [comment] 2020-10-26 04:07
@JaneFromSilabs @suveshpratapa , thanks for raising this issue and working towards a fix!

**Comment by suveshpratapa** [comment] 2020-10-26 14:51
@jwhui Can you please update the ot-br-posix pointer again?  It looks like it was updated to openthread/master, but the fix on the stack seems to have gone in after this pointer update.

**Comment by jwhui** [comment] 2020-10-26 15:13
> @jwhui Can you please update the ot-br-posix pointer again? It looks like it was updated to openthread/master, but the fix on the stack seems to have gone in after this pointer update.

@suveshpratapa , see #596.
